In [1]:
import numpy as np

In [2]:
np.array([[1,2,3],[4,5,6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [3]:
arr = np.array([[1,2,3],[4,5,6]])

In [4]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
arr[0]

array([1, 2, 3])

In [6]:
arr[1,:]

array([4, 5, 6])

In [7]:
arr[1,1:2]

array([5])

In [8]:
arr[1,1:]

array([5, 6])