# NumPy live coding Notebook

## NumPy arrays en matrices

In [1]:
import numpy as np

In [3]:
np.array([[1,2,3],[4,5,6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
arr = np.array([[1,2,3],[4,5,6]])

In [7]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

## Shape en transponeren

In [6]:
arr.shape

(2, 3)

In [7]:
arr.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [8]:
arr.T.shape

(3, 2)

## Indexatie en slicing

In [9]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
arr[0]

array([1, 2, 3])

In [6]:
arr[1,:]

array([4, 5, 6])

In [7]:
arr[1,1:2]

array([5])

In [8]:
arr[1,1:]

array([5, 6])

## arange, linspace, zeros, ones, eye

In [25]:
np.arange(0, 10, 1)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [29]:
np.linspace(0, 9, 10)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [30]:
np.linspace(0, 9, 50)

array([0.        , 0.18367347, 0.36734694, 0.55102041, 0.73469388,
       0.91836735, 1.10204082, 1.28571429, 1.46938776, 1.65306122,
       1.83673469, 2.02040816, 2.20408163, 2.3877551 , 2.57142857,
       2.75510204, 2.93877551, 3.12244898, 3.30612245, 3.48979592,
       3.67346939, 3.85714286, 4.04081633, 4.2244898 , 4.40816327,
       4.59183673, 4.7755102 , 4.95918367, 5.14285714, 5.32653061,
       5.51020408, 5.69387755, 5.87755102, 6.06122449, 6.24489796,
       6.42857143, 6.6122449 , 6.79591837, 6.97959184, 7.16326531,
       7.34693878, 7.53061224, 7.71428571, 7.89795918, 8.08163265,
       8.26530612, 8.44897959, 8.63265306, 8.81632653, 9.        ])

In [31]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [32]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [33]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## np.random

In [12]:
rand_arr = np.random.rand(100, 4)
rand_arr[:5,:]

array([[0.83632791, 0.84049071, 0.6600157 , 0.21052593],
       [0.17955582, 0.93350153, 0.7097402 , 0.00883758],
       [0.44421777, 0.49507887, 0.78558324, 0.94374768],
       [0.96470847, 0.67210779, 0.43854117, 0.41483878],
       [0.43211965, 0.5083066 , 0.86780039, 0.04901874]])

In [13]:
np.random.randn(5, 4)

array([[ 0.17238653, -0.64193961,  2.42161282,  0.57915733],
       [-0.45578727, -1.33402937,  1.00408368, -0.28416983],
       [ 0.17174903, -0.43160707, -1.30702262,  0.43283871],
       [ 0.18251531,  2.0058711 ,  0.4372713 ,  0.2536588 ],
       [-0.03981084,  0.48823382, -0.33422814, -0.99405468]])

In [14]:
np.random.randint(0, 10, size=(5,4))

array([[8, 6, 6, 3],
       [0, 4, 2, 8],
       [2, 6, 3, 9],
       [7, 4, 3, 4],
       [3, 8, 2, 5]])

## Vectoren

In [2]:
v = np.array([1,2,3,4])
v

array([1, 2, 3, 4])

In [3]:
v.shape

(4,)

In [4]:
v2 = np.array([[1,2,3,4]])
v2

array([[1, 2, 3, 4]])

In [5]:
v2.shape

(1, 4)

## Element-wise operaties

In [8]:
arr + 1

array([[2, 3, 4],
       [5, 6, 7]])

In [9]:
arr * 2

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [10]:
arr2 = np.ones((2,3)) * 3
arr2

array([[3., 3., 3.],
       [3., 3., 3.]])

In [11]:
arr * arr2

array([[ 3.,  6.,  9.],
       [12., 15., 18.]])

In [12]:
arr3 = np.ones((2,2)) * 3
arr * arr3

ValueError: operands could not be broadcast together with shapes (2,3) (2,2) 

## Matrix-vermenigvuldiging

In [13]:
arr4 = np.ones((3,2)) * 3
arr @ arr4

array([[18., 18.],
       [45., 45.]])

In [14]:
np.matmul(arr, arr4)

array([[18., 18.],
       [45., 45.]])

In [15]:
np.dot(arr, arr4)

array([[18., 18.],
       [45., 45.]])

In [17]:
v3 = np.array([3,3,3,3]).T
np.dot(v2, v3)

array([30])

## Pandas

In [1]:
import pandas as pd

In [2]:
my_dict = {'J':[1,4], 'F':[2,5], 'M':[3,6]}

In [3]:
df = pd.DataFrame(my_dict,index=['C1','C2'])

In [4]:
df

J  F  M
C1  1  2  3
C2  4  5  6

In [5]:
df['F']

C1    2
C2    5
Name: F, dtype: int64

In [6]:
df.loc['C1']

J    1
F    2
M    3
Name: C1, dtype: int64

In [7]:
df.iloc[0]

J    1
F    2
M    3
Name: C1, dtype: int64

In [10]:
arr = np.random.randn(100, 10)
df2 = pd.DataFrame(arr, columns='A B C D E F G H I J'.split())
df2.head()

A         B         C         D         E         F         G  \
0  0.453190  0.391058  0.741634 -0.068166  0.473388  1.037060 -0.874914   
1  0.892769 -0.620716 -0.468861 -2.371946 -0.187162 -0.184836  1.385094   
2  1.161478 -0.098232  0.814391 -0.784821  1.634919 -0.044909  1.696427   
3  1.098999  0.390531 -0.021613  1.127759 -1.969388 -0.679576 -1.170522   
4  0.538443 -1.672309  1.885588  1.396726 -0.830480  0.418241  2.211555   

          H         I         J  
0  0.962917  0.243284 -0.669673  
1 -2.488848  0.427331  0.358237  
2 -1.486163 -0.151533 -0.484939  
3  0.972975  0.786775 -1.201584  
4  0.166820 -0.429219 -0.174409

In [11]:
df2.to_csv('example')

In [12]:
df3 = pd.read_csv('example', index_col=0)
df3.head()

A         B         C         D         E         F         G  \
0  0.453190  0.391058  0.741634 -0.068166  0.473388  1.037060 -0.874914   
1  0.892769 -0.620716 -0.468861 -2.371946 -0.187162 -0.184836  1.385094   
2  1.161478 -0.098232  0.814391 -0.784821  1.634919 -0.044909  1.696427   
3  1.098999  0.390531 -0.021613  1.127759 -1.969388 -0.679576 -1.170522   
4  0.538443 -1.672309  1.885588  1.396726 -0.830480  0.418241  2.211555   

          H         I         J  
0  0.962917  0.243284 -0.669673  
1 -2.488848  0.427331  0.358237  
2 -1.486163 -0.151533 -0.484939  
3  0.972975  0.786775 -1.201584  
4  0.166820 -0.429219 -0.174409

In [13]:
df3.describe()

A           B           C           D           E           F  \
count  100.000000  100.000000  100.000000  100.000000  100.000000  100.000000   
mean     0.092336   -0.165505    0.032662   -0.094872    0.018168   -0.004098   
std      0.997113    0.975365    0.996640    1.045211    1.069012    0.997550   
min     -2.522216   -2.510621   -2.382006   -3.330368   -2.560492   -2.444414   
25%     -0.596166   -0.780621   -0.637183   -0.766547   -0.720732   -0.596700   
50%      0.142790   -0.208181    0.140557   -0.067519   -0.013673    0.044546   
75%      0.690705    0.424697    0.685546    0.524648    0.797575    0.729701   
max      2.584541    2.428004    2.829402    2.346404    2.250162    1.954509   

                G           H           I           J  
count  100.000000  100.000000  100.000000  100.000000  
mean     0.083788   -0.077595    0.010861   -0.128620  
std      1.061195    1.025310    1.067633    0.888642  
min     -3.470196   -2.488848   -2.378162   -2.614245  
25%     -0.547990   -0.767050   -0.791004   -0.708693  
50%      0.112373   -0.113994    0.080641   -0.167237  
75%      0.676061    0.638004    0.812590    0.425134  
max      2.457654    2.562281    2.508658    1.796199