# NumPy live coding Notebook

## NumPy arrays

In [10]:
import numpy as np

In [3]:
np.array([[1,2,3],[4,5,6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
arr = np.array([[1,2,3],[4,5,6]])

In [5]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

## Shape en transponeren

In [6]:
arr.shape

(2, 3)

In [7]:
arr.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [8]:
arr.T.shape

(3, 2)

## Indexatie en slicing

In [9]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
arr[0]

array([1, 2, 3])

In [6]:
arr[1,:]

array([4, 5, 6])

In [7]:
arr[1,1:2]

array([5])

In [8]:
arr[1,1:]

array([5, 6])

## arange, linspace, zeros, ones, eye

In [25]:
np.arange(0, 10, 1)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [29]:
np.linspace(0, 9, 10)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [30]:
np.linspace(0, 9, 50)

array([0.        , 0.18367347, 0.36734694, 0.55102041, 0.73469388,
       0.91836735, 1.10204082, 1.28571429, 1.46938776, 1.65306122,
       1.83673469, 2.02040816, 2.20408163, 2.3877551 , 2.57142857,
       2.75510204, 2.93877551, 3.12244898, 3.30612245, 3.48979592,
       3.67346939, 3.85714286, 4.04081633, 4.2244898 , 4.40816327,
       4.59183673, 4.7755102 , 4.95918367, 5.14285714, 5.32653061,
       5.51020408, 5.69387755, 5.87755102, 6.06122449, 6.24489796,
       6.42857143, 6.6122449 , 6.79591837, 6.97959184, 7.16326531,
       7.34693878, 7.53061224, 7.71428571, 7.89795918, 8.08163265,
       8.26530612, 8.44897959, 8.63265306, 8.81632653, 9.        ])

In [31]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [32]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [33]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## np.random

In [12]:
rand_arr = np.random.rand(100, 4)
rand_arr[:5,:]

array([[0.83632791, 0.84049071, 0.6600157 , 0.21052593],
       [0.17955582, 0.93350153, 0.7097402 , 0.00883758],
       [0.44421777, 0.49507887, 0.78558324, 0.94374768],
       [0.96470847, 0.67210779, 0.43854117, 0.41483878],
       [0.43211965, 0.5083066 , 0.86780039, 0.04901874]])

In [13]:
np.random.randn(5, 4)

array([[ 0.17238653, -0.64193961,  2.42161282,  0.57915733],
       [-0.45578727, -1.33402937,  1.00408368, -0.28416983],
       [ 0.17174903, -0.43160707, -1.30702262,  0.43283871],
       [ 0.18251531,  2.0058711 ,  0.4372713 ,  0.2536588 ],
       [-0.03981084,  0.48823382, -0.33422814, -0.99405468]])

In [14]:
np.random.randint(0, 10, size=(5,4))

array([[8, 6, 6, 3],
       [0, 4, 2, 8],
       [2, 6, 3, 9],
       [7, 4, 3, 4],
       [3, 8, 2, 5]])

## Vectoren

## Element-wise operaties

## Matrix-vermenigvuldiging

## Pandas

In [2]:
import pandas as pd

In [3]:
my_dict = {'J':[1,4], 'F':[2,5], 'M':[3,6]}

In [4]:
df = pd.DataFrame(my_dict,index=['C1','C2'])

In [5]:
df

J  F  M
C1  1  2  3
C2  4  5  6

In [6]:
df['F']

C1    2
C2    5
Name: F, dtype: int64

In [7]:
df.loc['C1']

J    1
F    2
M    3
Name: C1, dtype: int64

In [9]:
df.iloc[0]

J    1
F    2
M    3
Name: C1, dtype: int64

In [15]:
arr = np.random.randn(100, 10)
df2 = pd.DataFrame(arr, columns='A B C D E F G H I J'.split())
df2.head()

A         B         C         D         E         F         G  \
0 -0.017406 -0.449318  1.608980  0.012026  1.267261 -0.912026  1.091039   
1  0.376942 -1.552614  0.032979  0.693064 -1.293245 -0.440387 -0.469579   
2  1.764015  0.156742  0.053564  0.520691 -0.297894 -2.057930  0.368334   
3 -0.574043  1.384442  0.191348 -0.906562 -1.261570 -0.626248 -0.067375   
4 -2.222669  0.465922 -0.971500  0.755476  1.791976  0.284614 -0.875390   

          H         I         J  
0 -1.083208  0.432415  1.440303  
1 -1.643155 -0.116789  0.669484  
2 -1.381905 -0.814134  0.630846  
3  0.733461  1.409944 -0.916297  
4  0.175858 -0.483519  0.155714

In [16]:
df2.to_csv('example')

In [18]:
df3 = pd.read_csv('example', index_col=0)
df3.head()

A         B         C         D         E         F         G  \
0 -0.017406 -0.449318  1.608980  0.012026  1.267261 -0.912026  1.091039   
1  0.376942 -1.552614  0.032979  0.693064 -1.293245 -0.440387 -0.469579   
2  1.764015  0.156742  0.053564  0.520691 -0.297894 -2.057930  0.368334   
3 -0.574043  1.384442  0.191348 -0.906562 -1.261570 -0.626248 -0.067375   
4 -2.222669  0.465922 -0.971500  0.755476  1.791976  0.284614 -0.875390   

          H         I         J  
0 -1.083208  0.432415  1.440303  
1 -1.643155 -0.116789  0.669484  
2 -1.381905 -0.814134  0.630846  
3  0.733461  1.409944 -0.916297  
4  0.175858 -0.483519  0.155714