# NumPy live coding Notebook

## NumPy arrays en matrices

In [1]:
import numpy as np

In [2]:
np.array([[1,2,3],[4,5,6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [3]:
arr = np.array([[1,2,3],[4,5,6]])

In [4]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

## Shape en transponeren

In [5]:
arr.shape

(2, 3)

In [6]:
arr.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [7]:
arr.T.shape

(3, 2)

## Indexatie en slicing

In [8]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
arr[0]

array([1, 2, 3])

In [10]:
arr[1,:]

array([4, 5, 6])

In [11]:
arr[1,1:2]

array([5])

In [12]:
arr[1,1:]

array([5, 6])

## arange, linspace, zeros, ones, eye

In [13]:
np.arange(0, 10, 1)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [15]:
np.linspace(0, 9, 10)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [16]:
np.linspace(0, 9, 50)

array([0.        , 0.18367347, 0.36734694, 0.55102041, 0.73469388,
       0.91836735, 1.10204082, 1.28571429, 1.46938776, 1.65306122,
       1.83673469, 2.02040816, 2.20408163, 2.3877551 , 2.57142857,
       2.75510204, 2.93877551, 3.12244898, 3.30612245, 3.48979592,
       3.67346939, 3.85714286, 4.04081633, 4.2244898 , 4.40816327,
       4.59183673, 4.7755102 , 4.95918367, 5.14285714, 5.32653061,
       5.51020408, 5.69387755, 5.87755102, 6.06122449, 6.24489796,
       6.42857143, 6.6122449 , 6.79591837, 6.97959184, 7.16326531,
       7.34693878, 7.53061224, 7.71428571, 7.89795918, 8.08163265,
       8.26530612, 8.44897959, 8.63265306, 8.81632653, 9.        ])

In [17]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [18]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [19]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## np.random

In [20]:
rand_arr = np.random.rand(100, 4)
rand_arr[:5,:]

array([[0.74133738, 0.88795178, 0.16950136, 0.11393735],
       [0.4676044 , 0.64869194, 0.50929761, 0.98921833],
       [0.13705609, 0.49062149, 0.08507443, 0.92165941],
       [0.09801946, 0.59744137, 0.78466337, 0.19101801],
       [0.05332015, 0.79698846, 0.5338119 , 0.52573305]])

In [21]:
np.random.randn(5, 4)

array([[ 1.22519542,  0.72710474, -0.02724184,  0.21941931],
       [ 0.9597482 ,  0.37131325,  0.31187589,  0.26636733],
       [ 0.68710936,  0.34255352,  0.37806412, -1.27868983],
       [ 1.47136044, -0.97482229, -1.70786798,  2.24911164],
       [ 0.10678307, -0.5710492 ,  1.25635033,  0.28522195]])

In [22]:
np.random.randint(0, 10, size=(5,4))

array([[9, 2, 0, 4],
       [4, 2, 4, 6],
       [3, 0, 7, 8],
       [8, 9, 4, 2],
       [1, 8, 3, 8]])

## Vectoren

In [23]:
v = np.array([1,2,3,4])
v

array([1, 2, 3, 4])

In [24]:
v.shape

(4,)

In [25]:
v2 = np.array([[1,2,3,4]])
v2

array([[1, 2, 3, 4]])

In [26]:
v2.shape

(1, 4)

## Element-wise operaties

In [27]:
arr + 1

array([[2, 3, 4],
       [5, 6, 7]])

In [28]:
arr * 2

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [29]:
arr2 = np.ones((2,3)) * 3
arr2

array([[3., 3., 3.],
       [3., 3., 3.]])

In [30]:
arr * arr2

array([[ 3.,  6.,  9.],
       [12., 15., 18.]])

In [31]:
arr3 = np.ones((2,2)) * 3
arr * arr3

ValueError: operands could not be broadcast together with shapes (2,3) (2,2) 

## Matrix-vermenigvuldiging

In [32]:
arr4 = np.ones((3,2)) * 3
arr @ arr4

array([[18., 18.],
       [45., 45.]])

In [33]:
np.matmul(arr, arr4)

array([[18., 18.],
       [45., 45.]])

In [34]:
np.dot(arr, arr4)

array([[18., 18.],
       [45., 45.]])

In [35]:
v3 = np.array([3,3,3,3]).T
np.dot(v2, v3)

array([30])

## Pandas

In [36]:
import pandas as pd

In [37]:
my_dict = {'J':[1,4], 'F':[2,5], 'M':[3,6]}

In [38]:
df = pd.DataFrame(my_dict,index=['C1','C2'])

In [39]:
df

J  F  M
C1  1  2  3
C2  4  5  6

In [40]:
df['F']

C1    2
C2    5
Name: F, dtype: int64

In [41]:
df.loc[:,'F']

C1    2
C2    5
Name: F, dtype: int64

In [42]:
df['C1']

KeyError: 'C1'

In [44]:
df.loc['C1']

J    1
F    2
M    3
Name: C1, dtype: int64

In [43]:
df.loc['C1',:]

J    1
F    2
M    3
Name: C1, dtype: int64

In [ ]:
df.iloc[0]

In [ ]:
arr = np.random.randn(100, 10)
df2 = pd.DataFrame(arr, columns='A B C D E F G H I J'.split())
df2.head()

In [ ]:
df2.to_csv('example')

In [ ]:
df3 = pd.read_csv('example', index_col=0)
df3.head()

In [ ]:
df3.describe()